name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: AssembleDebug with Gradle
        run: ./gradlew assembleDebug --stacktrace
      - name: TestDebugUnitTest with Gradle
        run: ./gradlew testDebugUnitTest --stacktrace
